### PR TITLE
Bgc as string and second submitter

### LINKED ISSUE #101: Add submitter column to list of projects

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #101 and #94

### CODE REVIEW

**Comment by sverhoeven** [comment]
TODOS:

* [x] change schema
* [x] Migration script to adapt project to new schema
* [x] Correct example project
* [x] Rendering of second submitter
* [x] Rendering of MiBIG accession

Steps for roll out in production:
  * [x] docker-compose down +  git pull + docker-compose build
  * [x] Create backup of projects
  * [x] docker-compose up redis and db
  * [x] Run migration script to update all projects
  * [x] Validate all projects
  * [x] docker-compose up app
  * [ ] Manually update submitter fields for projects which now use multiple names in `submitter_name` field by editing project, filling `submitter_name_secondary` field and re-approving.

**Comment by sverhoeven** [comment]
@mschorn0713 Could you check if English is OK in [schema changes](https://github.com/iomega/paired-data-form/pull/110/files#diff-03428cfd4f3733310523746e333c5a03).?

**Comment by sverhoeven** [comment]
@justinjjvanderhooft If there is a submitter and secondary submitter for a project I count them both as having 0.5 contribution in the statistics page. Is this OK? 

Or should I count them as 1 each per project. Which will cause submitter sum to be greater than number of projects.

**Comment by justinjjvanderhooft** [comment]
Let's make it 1 per project. Then it is clear to how many projects someone
contributed. In the end, it remains a bit arbitrary as some projects are
small and others are huge....

**Comment by sverhoeven** [comment]
Also fixes #106 in https://github.com/iomega/paired-data-form/pull/110/commits/8437cfef1c4ed41359d357f44f6fd4cef20684df commit

**Comment by sverhoeven** [comment]
Successfully performed the migration steps in the CHANGELOG on a local copy of the production site.
Ready for rollout in production

**Comment by sverhoeven** [comment]
On the server JSON files can be edited with 

```shell
docker-compose exec api sh
apk --no-cache add nano
nano /data/approved/<invalid>.json
```

**Pull request merged**
